---
title: Jaqueline Lavitt Design
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  home-page:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: artists
  values:
    Project Subtitle: 
    Image: 
    Link: 
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
theme: minima
sass:
  sass_dir: "./_scss"
plugins:
- jekyll-feed
